scenario:
  id: energy
  name: energy management

problem:
  n_var: 385
  n_eq: 193
  n_ineq: 483
  N: 96
  n_state: 1
  m_input: 2
  seed: 2026
  Delta_t: 0.25
  b_bess: 500.0
  p_k: 0.1
  p_p: 19.19
  eta: 10.0
  mu: 0.8
  gamma: 50.0
  S_e: 700.0
  S_B: 100.0
  kappa_D: 0.1
  kappa_g: 10.0
  delta: 0.7
  sigma_min: 0.2
  sigma_max: 0.8
  B_min: -700.0
  B_max: 700.0
  r_min: 0.000001
  r_ext: 0.02
  S_m: 100.0
  sigma_0: 0.5
  sigma_N_min: 0.5

data:
  root_subdir: data/energy
  n_samples: 20000
  train_percent: 0.8
  val_percent: 0.1
  test_percent: 0.1

neural_net:
  hidden_layers: [512, 512]
  mode: correction

optimizer:
  learning_rate: 0.001
  decay_rate: 0.9
  transition_steps: 1000
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  max_consecutive_errors: 1

training:
  batch_size: 256
  n_epochs: 2000
  n_admm: 40
  gamma_r: 100.0
  gamma_p: 1.0
  gamma_c: 1.0
  gamma_s: 1000.0
  eval_step: 2000

admm:
  max_iter: 1000
  tolerance: 0.001
  rho: 10.0
  solver: CLARABEL
